import type { Metadata } from "next";
import { Cantata_One, Carattere, Calistoga } from "next/font/google";
import "./globals.css";

const cantataOne = Cantata_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-cantata-one",
});

const carattere = Carattere({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-carattere",
});

const calistoga = Calistoga({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-calistoga",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${cantataOne.variable} ${calistoga.variable} ${carattere.variable} ${cantataOne.className} antialiased max-w-screen overflow-x-hidden relative `}
      >
        {children}
      </body>
    </html>
  );
}
